format = """
$all\
"""


[directory]
style = "fg:#ea9b2c"
truncation_length = 8
truncate_to_repo = false


[git_branch]
format = "[$symbol$branch]($style) "
style = "#29dcfb"


[git_status]
format = '( [$all_status$ahead_behind](fg:#0098ff) )'


[character]
success_symbol = "[❯](bold #29dcfb)"
error_symbol = "[❯](bold #e13f00)"

[status]
style = "fg:#e13f00"

[cmd_duration]
format = "[$duration]($style) "
style = "#d9c68d"


[nodejs]
disabled = true


[golang]
disabled = true
